version: '3'
services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project
    networks:
      - item-network
  school:
    build: ./school_service/
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
      - redis-auth
    networks:
      - item-network
  redis-auth:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - item-network
  auth:
    build: ./auth_service/
    ports:
      - '8081:8081'
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    depends_on:
      - redis-auth
    networks:
      - item-network
networks:
  item-network:
